FROM python:3.11.5-slim-bullseye

ENV PIP_DISABLE_PIP_VERSION_CHECK 1
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /code

COPY requirements.txt .

RUN apt-get update -y && \
    pip install --upgrade pip && \
    pip install -r requirements.txt

COPY . .

RUN python manage.py makemigrations
RUN python manage.py migrate --run-syncdb

ENTRYPOINT ["python", "manage.py", "runserver", "0.0.0.0:8000"]
