services:
  family_budget:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - .:/code
    environment:
      - DJANGO_SETTINGS_MODULE=family_budget.settings.development
    ports:
      - 8000:8000